language: generic  # Otherwise the g++ command gets overwritten
dist: trusty
sudo: false
jobs:
  include:
  - stage: check-format
    name: JavaScript Format
    script: diff <(clang-format -style=file $(find -name '*.js')) <(cat $(find -name '*.js'))
  - name: C++ Format
    script: diff <(clang-format -style=file $(find . -name '*.cpp' -or -name '*.h')) <(cat $(find . -name '*.cpp' -or -name '*.h'))
  - stage: build
    name: Build WebExtension
    script: make webextension.zip
  - name: Build Native Application
    env:
    - CXX=g++-6
    script: make native-x86-64.tar.gz
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - qtbase5-dev
        - g++-6
