language: c++
jobs:
  include:
  - stage: check-format
    script: diff <(clang-format -style=file $(find -name '*.js')) <(cat $(find -name '*.js'))
  - script: diff <(clang-format -style=file $(find . -name '*.cpp' -or -name '*.h')) <(cat $(find . -name '*.cpp' -or -name '*.h'))
  - stage: deploy
    script: make
